spring:
  profiles:
    active:
      - dog
      - EN
      - prod
guru:
  username: YmlUserName
  password: YmlPassword
  jdbcUrl: YmlUrl

---
spring:
  profiles: prod
guru:
  username: ProdUserName
  password: ProdPassword
  jdbcUrl: ProdUrl